import { describe, expect, it } from "vitest";
import {
  type Bump,
  type Deprecation,
  type ReportPair,
  apiChanges,
  changesetBump,
  checkApiDiff,
  formatFindings,
  nextMinor,
  normalizeSignature,
  parseApiReport,
  parseDeprecations,
} from "./api-diff.js";

/** The shape API Extractor writes: a fenced `ts` block of tagged, alphabetised declarations. */
function report(body: string): string {
  return `## API Report File for "@hyperfixation/core"

> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).

\`\`\`ts

${body}
\`\`\`
`;
}

const BASELINE = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);

function pair(head: string, overrides: Partial<ReportPair> = {}): ReportPair {
  return {
    package: "@hyperfixation/core",
    version: "0.1.1",
    file: "packages/core/etc/core.api.md",
    baseline: BASELINE,
    head,
    ...overrides,
  };
}

const REMOVED = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);

const ENTRY: Deprecation = {
  package: "@hyperfixation/core",
  symbol: "flowOriginRef",
  since: "0.1.1",
  removeIn: "0.2.0",
};

function check(head: string, deprecations: readonly Deprecation[], bump: Bump) {
  return checkApiDiff({ reports: [pair(head)], deprecations, bump });
}

describe("parseApiReport", () => {
  it("keys members of a declaration and carries the @deprecated tag", () => {
    const declarations = parseApiReport(BASELINE);
    expect([...declarations.keys()].sort()).toEqual([
      "ACTIVITY_LIST_OPERATION",
      "TaskCreateOptions",
      "Verdict",
      "flowOriginRef",
    ]);
    expect(declarations.get("flowOriginRef")?.deprecated).toBe(true);
    expect(declarations.get("ACTIVITY_LIST_OPERATION")?.deprecated).toBe(false);
    expect([...(declarations.get("TaskCreateOptions")?.members.keys() ?? [])].sort()).toEqual([
      "",
      "dueAt",
      "key",
      "title",
    ]);
  });
});

describe("normalizeSignature", () => {
  it("sorts the members of a top-level union but leaves a nested one alone", () => {
    expect(normalizeSignature('"b" | "a"')).toBe(normalizeSignature('"a" | "b"'));
    expect(normalizeSignature("Array<b | a>")).not.toBe(normalizeSignature("Array<a | b>"));
  });
});

describe("checkApiDiff", () => {
  it("fails a removed export with no deprecations.json entry", () => {
    const findings = check(REMOVED, [], "minor");
    expect(findings).toHaveLength(1);
    expect(findings[0]?.symbol).toBe("flowOriginRef");
    expect(findings[0]?.kind).toBe("removed");
    expect(findings[0]?.problems.join("\n")).toContain("no deprecations.json entry");
  });

  it("fails a removed export carried by a patch changeset", () => {
    const findings = check(REMOVED, [ENTRY], "patch");
    expect(findings).toHaveLength(1);
    expect(findings[0]?.problems).toEqual([
      expect.stringContaining("needs a minor changeset (found: patch)"),
    ]);
  });

  it("passes a removed export with an entry and a minor changeset", () => {
    expect(check(REMOVED, [ENTRY], "minor")).toEqual([]);
  });

  it("fails an entry whose since has not shipped, or whose removeIn is before the next minor", () => {
    const ahead = check(REMOVED, [{ ...ENTRY, since: "0.2.0" }], "minor");
    expect(ahead[0]?.problems).toEqual([expect.stringContaining("ahead of")]);
    const early = check(REMOVED, [{ ...ENTRY, removeIn: "0.1.2" }], "minor");
    expect(early[0]?.problems).toEqual([expect.stringContaining("earlier than the next minor")]);
  });

  it("fails a removal of a symbol that was never tagged @deprecated in the baseline", () => {
    const head = report(`// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);
    const findings = check(head, [{ ...ENTRY, symbol: "ACTIVITY_LIST_OPERATION" }], "minor");
    expect(findings).toHaveLength(1);
    expect(findings[0]?.problems).toEqual([expect.stringContaining("no @deprecated tag")]);
  });

  it("passes an added export", () => {
    const head = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public
export function archiveDecisionKey(recordType: string): string;

// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    optional?: boolean;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);
    expect(check(head, [], "patch")).toEqual([]);
  });

  it("passes a report whose declarations, members and union arms only moved", () => {
    const head = report(`// @public @deprecated
export interface TaskCreateOptions {
    title: string;
    key?: string;
    dueAt?: Date;
}

// @public
export type Verdict = "rejected" | "approved";

// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";
`);
    expect(apiChanges(pair(head))).toEqual([]);
    expect(check(head, [], "patch")).toEqual([]);
  });

  it("treats a retyped member like a removal", () => {
    const head = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: number;
}

// @public
export type Verdict = "approved" | "rejected";
`);
    const changes = apiChanges(pair(head));
    expect(changes).toEqual([
      expect.objectContaining({ symbol: "TaskCreateOptions", member: "title", kind: "retyped" }),
    ]);
    const findings = check(head, [], "minor");
    expect(findings[0]?.kind).toBe("retyped");
    expect(findings[0]?.problems.join("\n")).toContain("no deprecations.json entry");
  });

  it("passes a const whose literal grew, which is what adding an hf command does", () => {
    const head = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list, activity.count";

// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);
    expect(apiChanges(pair(head))).toEqual([]);
    expect(check(head, [], "patch")).toEqual([]);
  });

  it("still reports a type alias that was retyped, const or not", () => {
    const head = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public @deprecated
export function flowOriginRef(runId: string, key: string): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved";
`);
    expect(apiChanges(pair(head))).toEqual([
      {
        package: "@hyperfixation/core",
        file: "packages/core/etc/core.api.md",
        symbol: "Verdict",
        member: "",
        kind: "retyped",
      },
    ]);
  });

  it("passes a signature that only gained a trailing optional parameter", () => {
    const head = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public @deprecated
export function flowOriginRef(runId: string, key: string, attempt?: number): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);
    expect(apiChanges(pair(head))).toEqual([]);
    expect(check(head, [], "patch")).toEqual([]);
  });

  it("reports a parameter made required, renamed or inserted before the existing ones", () => {
    const required = report(`// @public
export const ACTIVITY_LIST_OPERATION = "activity.list";

// @public @deprecated
export function flowOriginRef(runId: string, key: string, attempt: number): string;

// @public @deprecated
export interface TaskCreateOptions {
    dueAt?: Date;
    key?: string;
    title: string;
}

// @public
export type Verdict = "approved" | "rejected";
`);
    expect(apiChanges(pair(required))).toEqual([
      expect.objectContaining({ symbol: "flowOriginRef", kind: "retyped" }),
    ]);

    const inserted = required.replace(
      "runId: string, key: string, attempt: number",
      "attempt?: number, runId: string, key: string",
    );
    expect(apiChanges(pair(inserted))).toEqual([
      expect.objectContaining({ symbol: "flowOriginRef", kind: "retyped" }),
    ]);
  });
});

describe("a const holding a set of string literals", () => {
  /** How `packages/cli/etc/cli.api.md` prints `hf`'s command list and the usage text beside it. */
  const commands = (tuple: string, usage: string): string =>
    report(`// @public
export const COMMANDS: readonly ${tuple};

// @public
export const USAGE = "${usage}";
`);

  const BEFORE = commands(
    '["new", "migrate", "deploy"]',
    "hf new <name>\\n  hf migrate\\n  hf deploy <name>\\n",
  );

  const cli = (head: string): ReportPair => ({
    package: "@hyperfixation/cli",
    version: "0.1.4",
    file: "packages/cli/etc/cli.api.md",
    baseline: BEFORE,
    head,
  });

  const ADDED = commands(
    '["new", "migrate", "deploy", "doctor"]',
    "hf new <name>\\n  hf migrate\\n  hf deploy <name>\\n  hf doctor\\n",
  );
  const REORDERED = commands(
    '["deploy", "new", "migrate"]',
    "hf deploy <name>\\n  hf new <name>\\n  hf migrate\\n",
  );
  const DROPPED = commands(
    '["new", "migrate"]',
    "hf new <name>\\n  hf migrate\\n  hf deploy <name>\\n",
  );

  it("passes an added command, which is what #98 had to excuse", () => {
    expect(apiChanges(cli(ADDED))).toEqual([]);
    expect(checkApiDiff({ reports: [cli(ADDED)], deprecations: [], bump: "patch" })).toEqual([]);
  });

  it("passes a tuple whose members only moved", () => {
    expect(apiChanges(cli(REORDERED))).toEqual([]);
  });

  it("fails a removed command, naming it", () => {
    expect(apiChanges(cli(DROPPED))).toEqual([
      expect.objectContaining({ symbol: "COMMANDS", literalMember: "deploy", kind: "removed" }),
    ]);
    const findings = checkApiDiff({ reports: [cli(DROPPED)], deprecations: [], bump: "patch" });
    expect(findings).toHaveLength(1);
    expect(formatFindings(findings)).toContain("COMMANDS.deploy removed");
    expect(findings[0]?.problems.join("\n")).toContain(
      "no deprecations.json entry for @hyperfixation/cli COMMANDS.deploy",
    );
    expect(findings[0]?.problems.join("\n")).toContain("needs a minor changeset");
  });

  it("passes a removed command announced as COMMANDS.<name>, with no tag to carry", () => {
    const entry: Deprecation = {
      package: "@hyperfixation/cli",
      symbol: "COMMANDS.deploy",
      since: "0.1.4",
      removeIn: "0.2.0",
    };
    expect(checkApiDiff({ reports: [cli(DROPPED)], deprecations: [entry], bump: "minor" })).toEqual(
      [],
    );
  });

  it("keeps excusing the usage text on its own, and reports a tuple replaced wholesale", () => {
    const usageOnly = commands('["new", "migrate", "deploy"]', "a rewritten usage screen\\n");
    expect(apiChanges(cli(usageOnly))).toEqual([]);
    const widened = commands("string[]", "hf new <name>\\n  hf migrate\\n  hf deploy <name>\\n");
    expect(apiChanges(cli(widened))).toEqual([
      expect.objectContaining({ symbol: "COMMANDS", kind: "retyped" }),
    ]);
  });
});

describe("changesetBump", () => {
  it("takes the largest bump across the PR's changesets", () => {
    const patch = '---\n"@hyperfixation/core": patch\n---\n\nA fix.\n';
    const minor = '---\n"@hyperfixation/core": minor\n---\n\nA removal.\n';
    expect(changesetBump([])).toBe("none");
    expect(changesetBump([patch])).toBe("patch");
    expect(changesetBump([patch, minor])).toBe("minor");
  });
});

describe("versions", () => {
  it("makes the next minor the breaking release at 0.x", () => {
    expect(nextMinor("0.1.1")).toBe("0.2.0");
    expect(nextMinor("1.2.3")).toBe("1.3.0");
  });
});

describe("parseDeprecations", () => {
  it("accepts the committed empty file and refuses a row missing a field", () => {
    expect(parseDeprecations("[]")).toEqual([]);
    expect(() => parseDeprecations('[{"package":"a","symbol":"b","since":"0.1.0"}]')).toThrow(
      /removeIn/,
    );
  });
});
