export const START = "<!-- plan-sync:start -->";
export const END = "<!-- plan-sync:end -->";

export const REPOS = [
  { key: "core", slug: "grahamlutz/hyperfixation-core" },
  { key: "template", slug: "grahamlutz/hyperfixation-template" },
] as const;

export type Repo = (typeof REPOS)[number];

export type MergedPr = {
  readonly repo: Repo;
  readonly number: number;
  readonly title: string;
  readonly body: string;
  readonly mergedAt: string;
};

/** `"<repo key>#<number>"` → chunk id, for the PRs that predate the `Chunk:` convention. */
export type ChunkMap = Readonly<Record<string, string>>;

export type ChunkRow = { readonly chunk: string; readonly prs: readonly MergedPr[] };

const CHUNK_LINE = /^[ \t]*Chunk:[ \t]*(\S+)[ \t]*\r?$/m;

export function prKey(pr: MergedPr): string {
  return `${pr.repo.key}#${pr.number}`;
}

/**
 * A chunk id is only ever read, never inferred: a `Chunk:` line in the body, or an entry in the
 * checked-in map for a PR merged before the convention existed. Anything else is not a chunk PR.
 */
export function chunkOf(pr: MergedPr, map: ChunkMap = {}): string | undefined {
  const mapped = map[prKey(pr)];
  if (mapped !== undefined) return mapped;
  return CHUNK_LINE.exec(pr.body)?.[1];
}

export function statusRows(prs: readonly MergedPr[], map: ChunkMap = {}): ChunkRow[] {
  const byChunk = new Map<string, MergedPr[]>();
  for (const pr of prs) {
    const chunk = chunkOf(pr, map);
    if (chunk === undefined) continue;
    const row = byChunk.get(chunk) ?? [];
    row.push(pr);
    byChunk.set(chunk, row);
  }
  return [...byChunk]
    .map(([chunk, row]) => ({
      chunk,
      prs: [...row].sort((a, b) => a.mergedAt.localeCompare(b.mergedAt) || a.number - b.number),
    }))
    // Chunk ids read as the order doc writes them — `0`, `D1`, `D2`, … `E5`, `misc`.
    .sort((a, b) => a.chunk.localeCompare(b.chunk, "en", { numeric: true }));
}

function cell(text: string): string {
  return text.replaceAll("|", "\\|");
}

function link(pr: MergedPr): string {
  return `[${pr.repo.key} #${pr.number}](https://github.com/${pr.repo.slug}/pull/${pr.number})`;
}

export function renderTable(rows: readonly ChunkRow[]): string {
  const lines = [
    "<!-- Generated by `pnpm plan:sync` from merged PR bodies' `Chunk:` lines. Do not edit. -->",
    "",
    "| Chunk | PRs | Merged | Summary |",
    "|---|---|---|---|",
  ];
  for (const { chunk, prs } of rows) {
    const merged = prs.at(-1)?.mergedAt.slice(0, 10) ?? "";
    const summary = prs[0]?.title ?? "";
    lines.push(`| ${cell(chunk)} | ${prs.map(link).join(", ")} | ${merged} | ${cell(summary)} |`);
  }
  if (rows.length === 0) lines.push("| — | — | — | no merged PR carries a `Chunk:` line yet |");
  return lines.join("\n");
}

function only(doc: string, marker: string): number {
  const at = doc.indexOf(marker);
  if (at === -1) throw new Error(`The doc has no ${marker} marker.`);
  if (doc.indexOf(marker, at + marker.length) !== -1) {
    throw new Error(`The doc has more than one ${marker} marker.`);
  }
  return at;
}

/** Everything outside the markers — including the hand-written `> **Built …**` notes — is kept. */
export function replaceBlock(doc: string, block: string): string {
  const start = only(doc, START);
  const end = only(doc, END);
  if (end < start + START.length) throw new Error(`${END} comes before ${START}.`);
  return `${doc.slice(0, start + START.length)}\n${block.trim()}\n${doc.slice(end)}`;
}
